<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Where is CL ?</title>
    <?php include "presentation/head.phtml" ?>
</head>
<body class="bg-light">

<div class="container">
    <div class="row">
        <div class="col"><h1>#whereiscl</h1></div>
    </div>
    <?php include "search.php"; ?>
    <div class="row">
        <div class="col-6"><a href="/donate.php">To donate, simply smile.</a></div>
        <div class="col-6">For support: <a href="https://twitter.com/darkbelg">@Darkbelg</a></div>
    </div>
</div>
</body>
</html>
