<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!--    <script src="js/jquery-3.2.1.js"></script>-->
    <!--    <script src="js/countdown/jquery.countdown.js"></script>-->
    <!--    <script src="js/script.js"></script>-->
    <link rel="stylesheet" href="css/style.css">
    <title>Where is CL ?</title>
    <script src="js/script.js"></script>
</head>
<body>
<div class="container">
    <h1>#whereiscl</h1>
    <!--    <div class="albumrelease"></div>-->
    <!--    <div class="bestalbumcomebacktime"></div>-->
    <p>Quote of the day:<br/><q>+</q></p>

    <h2>Lifted is one year.</h2>
    <iframe height="315" width="560" src="https://www.youtube-nocookie.com/embed/Mr29X77OA5g?rel=0" frameborder="0" allowfullscreen></iframe>
    <p class="lifted"></p>

    <h2>Want to donate ?</h2>
    <p><a href="http://support.operationsmile.org/site/TR?pg=fund&fr_id=1030&pxfid=39223">Operation Smile!</a></p>
    <img src="https://media.giphy.com/media/vdjgl76N7dovS/giphy.gif" alt="">
    <div><p>More to come...</p></div>
</div>

</body>
</html>