<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Where is CL ?</title>
    <!--    CSS         -->
    <!--    Bootstrap   -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!--    Custom      -->
    <link rel="stylesheet" href="css/style.css">
    <!--    Javascript  -->
    <!--    Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-109821873-1"></script>
    <!--    Bootstrap   -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <!--    Custom      -->
    <script src="js/script.js"></script>
</head>
<body class="bg-light">

<div class="container">
    <div class="row">
        <div class="col"><h1>#whereiscl</h1></div>
    </div>
    <div class="row">
        <div class="col"><h2>Cambodja 17/12/16</h2>
        </div>
    </div>
    <?php include "searchOld.php"; ?>
    <div class="row">
        <div class="col"><a href="https://twitter.com/darkbelg">@Darkbelg</a></div>
    </div>
</div>
</body>
</html>
