<?php echo $html; ?>

    <script>
    // 3. This function creates an <iframe> (and YouTube player)
    //    after the API code downloads.
    var player;

    function fancamvideos() {

        <?php foreach ($searchResponses as $key => $searchResponse) {
        $date = $searchResponses[$key]["date"];

        for ($i = 0; $i < 3; $i++) {
            $idVideo = $searchResponse["items"][$i];
            $id = $date + $i;
            print('player = new YT.Player("' . $id . '", { videoId: "' . $idVideo . '" });');
        }
    }
        ?>
    }


<!--        --><?php //$j =1 ?>
<!--        -->
<!--        --><?php //foreach($fancam as $video): ?>
//
//    player = new YT.Player('fancam' + <?php //echo $j ?>//, {
//        videoId: '<?php //echo $video?>//'
//    });
//    <?php //$j ++;?>
<!--    --><?php //endforeach ?>
//    }
    
    </script>