<?php
$html = "";

foreach ($concerts as $concert) {
    $html .= '<div class="row">';
    $html .= '<div class="col-12"><h2>' . $concert->getName() . ' <span>Date: '. $concert->getformattedDate() . '</span></h2></div>';

    foreach ($concert->getFancams() as $key => $fancam) {
        $id = $concert->getDate().$key;
        $html .= '<div class="col-12 col-sm-6 col-lg-4  fancam" id="' . $id . '"><a target="_blank" href="https://www.youtube.com/watch?v=' . $fancam->getVideoID() . '"><img class="img-fluid" src="' . $fancam->getThumbnail() . '" alt ="' . $fancam->getVideoTitle() . '" />' . $fancam->getVideoTitle() . '</a></div>';
    }
    
    $html .= '</div>';
}

echo $html; ?>
